[update]
tasks = ["code", "transform", "normalize"]

[update.code]
codePaths = ["../Sources", "App"]
localizablePaths = ["../Sources", "App"]
defaultToKeys = false
additive = true
unstripped = false
plistArguments = true

[update.transform]
codePaths = ["../Sources", "App"]
localizablePaths = ["../Sources", "App"]
transformer = "swiftgenStructured"
supportedLanguageEnumPath = "../Sources/Resources"
typeName = "BartyCrouch"
translateMethodName = "translate"

[update.normalize]
paths = ["../Sources", "App"]
sourceLocale = "en"
harmonizeWithSource = true
sortByKeys = true

[lint]
paths = ["../Sources", "App"]
duplicateKeys = true
emptyValues = true
