name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test-macos:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2

      - name: Run tests
        run: |
          xcodebuild test \
            -project OpenFocusTimer/OpenFocusTimer.xcodeproj \
            -scheme macOSApp \
            -destination 'platform=macOS'

  test-ios:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2

      - name: Run tests
        run: |
          xcodebuild test \
            -project OpenFocusTimer/OpenFocusTimer.xcodeproj \
            -scheme iOSApp \
            -destination 'platform=iOS Simulator,name=iPhone 13'
